# Generated by Django 3.0.3 on 2020-03-01 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name_plural': 'abilities',
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('power', models.IntegerField()),
                ('accuracy', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Nature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('increased_stat', models.CharField(blank=True, choices=[('attack', 'attack'), ('defense', 'defense'), ('special_attack', 'special attack'), ('special_defense', 'special defense'), ('speed', 'speed')], max_length=16)),
                ('decreased_stat', models.CharField(blank=True, choices=[('attack', 'attack'), ('defense', 'defense'), ('special_attack', 'special attack'), ('special_defense', 'special defense'), ('speed', 'speed')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('immunities', models.ManyToManyField(blank=True, related_name='no_effect_against', to='battle_simulator.Type')),
                ('resistances', models.ManyToManyField(blank=True, related_name='weak_against', to='battle_simulator.Type')),
                ('weaknesses', models.ManyToManyField(blank=True, related_name='strong_against', to='battle_simulator.Type')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('hp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('special_attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('special_defense', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('type1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='species1', to='battle_simulator.Type')),
                ('type2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='species2', to='battle_simulator.Type')),
            ],
            options={
                'verbose_name_plural': 'species',
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=50)),
                ('iv_hp', models.IntegerField(default=15)),
                ('iv_attack', models.IntegerField(default=15)),
                ('iv_special_attack', models.IntegerField(default=15)),
                ('iv_defense', models.IntegerField(default=15)),
                ('iv_special_defense', models.IntegerField(default=15)),
                ('iv_speed', models.IntegerField(default=15)),
                ('ev_hp', models.IntegerField(default=20)),
                ('ev_attack', models.IntegerField(default=20)),
                ('ev_special_attack', models.IntegerField(default=20)),
                ('ev_defense', models.IntegerField(default=20)),
                ('ev_special_defense', models.IntegerField(default=20)),
                ('ev_speed', models.IntegerField(default=20)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='battle_simulator.Ability')),
                ('moves', models.ManyToManyField(to='battle_simulator.Move')),
                ('nature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='battle_simulator.Nature')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='battle_simulator.Species')),
            ],
            options={
                'verbose_name_plural': 'pokemon',
            },
        ),
        migrations.AddField(
            model_name='move',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='battle_simulator.Type'),
        ),
    ]
