# Generated by Django 3.0.3 on 2020-02-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle_simulator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nature',
            name='decreased_stat',
            field=models.CharField(blank=True, choices=[('attack', 'attack'), ('defense', 'defense'), ('special_attack', 'special attack'), ('special_defense', 'special defense'), ('speed', 'speed')], max_length=16),
        ),
        migrations.AddField(
            model_name='nature',
            name='increased_stat',
            field=models.CharField(blank=True, choices=[('attack', 'attack'), ('defense', 'defense'), ('special_attack', 'special attack'), ('special_defense', 'special defense'), ('speed', 'speed')], max_length=16),
        ),
    ]
