# Generated by Django 3.0.5 on 2020-05-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle_simulator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='damage_class',
            field=models.CharField(choices=[('PH', 'Physical'), ('SP', 'Special'), ('ST', 'Status')], default='PH', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='move',
            name='pp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='move',
            name='priority',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
