# Generated by Django 3.0.6 on 2020-07-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_battlelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
