# Generated by Django 3.2.4 on 2021-06-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0005_move_nerf_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='is_noteworthy',
            field=models.BooleanField(default=False),
        ),
    ]
