# Generated by Django 3.2.4 on 2021-06-27 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0006_move_is_noteworthy'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='evolves_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokemon.species'),
        ),
    ]
