# Generated by Django 3.2.4 on 2021-07-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0007_species_evolves_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='cache',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
